spring.application.name=TransactionHistoryService
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/payment_service
spring.datasource.username=postgres
spring.datasource.password=laith7525
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Artemis
spring.artemis.broker-url=tcp://localhost:61616
spring.artemis.user=admin
spring.artemis.password=admin

#Liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

#Account URL Prefix
account-service.url=http://localhost:8081

