spring.application.name=AccountService

#Server
server.port=${SERVER_PORT}

#Database
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#Spring JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

#Artemis
spring.artemis.broker-url=tcp://${ARTEMIS_HOST}:${ARTEMIS_PORT}
spring.artemis.user=${ARTEMIS_USERNAME}
spring.artemis.password=${ARTEMIS_PASSWORD}

#Customer Service
customer-service.url=${CUSTOMER_SERVICE_URL}

#Queue Names
process-transfer-queue=process-transfer
transfer-completed-queue=transfer-completed
transfer-failed-queue=transfer-failed