package com.example.customerservice.Controller;


import com.example.customerservice.Model.Dto.UserCreationDto;
import com.example.customerservice.Model.Dto.UserDto;
import com.example.customerservice.Service.IUserService;
import io.swagger.v3.oas.annotations.Operation;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

import java.util.ArrayList;
import java.util.List;

@RestController
@RequestMapping("/users")
public class UserController {

    private final IUserService userService;

    UserController(IUserService userService) {
        this.userService = userService;
    }

    @Operation(description = "returns a list of all users in the user db")
    @GetMapping("")
    public ResponseEntity<List<UserDto>> getAllUsers() {

        List<UserDto> allUsers = new ArrayList<>(userService.getAllUsers());
        return ResponseEntity.ok(allUsers);

    }

    @Operation(description = "returns the information of a specific user using id")
    @GetMapping("/{id}")
    public ResponseEntity<UserDto> getUserById(@PathVariable Long id) {

        return ResponseEntity.ok(userService.getUserById(id));
    }

    @Operation(description = "creates a user , id is generated by jpa , not part of RequestBody")
    @PostMapping("")
    public ResponseEntity<UserDto> createUser(@RequestBody @Valid UserCreationDto userCreationDto) {
        return new ResponseEntity<UserDto>(userService.createUser(userCreationDto) , HttpStatus.CREATED);
    }

}
