package com.example.customerservice.controller;

import com.example.customerservice.mapper.UserMapper;
import com.example.customerservice.model.UserCreationModel;
import com.example.customerservice.model.UserModel;
import com.example.customerservice.resource.request.UserCreationResource;
import com.example.customerservice.resource.response.UserResource;
import com.example.customerservice.service.UserService;
import io.swagger.v3.oas.annotations.Operation;
import jakarta.validation.Valid;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;


@Slf4j
@RestController
@RequestMapping("/users")
public class UserController {

    private final UserService userService;
    private final UserMapper userMapper;

    UserController(UserService userService, UserMapper userMapper) {
        this.userService = userService;
        this.userMapper = userMapper;
    }

    @Operation(description = "returns a list of all users in the user db")
    @GetMapping("")
    public ResponseEntity<Page<UserResource>> getAllUsers(
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "5") int size
    ) {
        log.info("getAllUsers endpoint invoked");
        Pageable pageable = PageRequest.of(page , size);

        Page<UserModel> userModels = userService.getAllUsers(pageable);

        Page<UserResource> response = userModels.map(userMapper::toUserResource);

        log.info("returning users..");
        return new ResponseEntity<>(response , HttpStatus.OK);

    }

    @Operation(description = "returns the information of a specific user using id")
    @GetMapping("/{id}")
    public ResponseEntity<UserResource> getUserById(@PathVariable Long id) {

        log.info("getUserById endpoint invoked");

        UserModel userModel = userService.getUserById(id);

        log.info("returning User");

        return ResponseEntity.ok(userMapper.toUserResource(userModel));
    }

    @Operation(description = "creates a user , id is generated by jpa , not part of RequestBody")
    @PostMapping("")
    public ResponseEntity<UserResource> createUser(@RequestBody @Valid UserCreationResource userCreationResource) {

        log.info("createUser endpoint invoked");

        UserCreationModel userCreationModel = userMapper.toUserCreationModel(userCreationResource);

        UserModel createdUser = userService.createUser(userCreationModel);

        return new ResponseEntity<>(userMapper.toUserResource(createdUser), HttpStatus.CREATED);
    }

}
