spring.application.name=ProjectGateway

#Server
server.port=${SERVER_PORT:8084}

#CustomerService
spring.cloud.gateway.server.webmvc.routes[0].id=CustomerService
spring.cloud.gateway.server.webmvc.routes[0].uri=${CUSTOMER_SERVICE_URL}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/users/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

#AccountService
spring.cloud.gateway.server.webmvc.routes[1].id=AccountService
spring.cloud.gateway.server.webmvc.routes[1].uri=${ACCOUNT_SERVICE_URL}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/accounts/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

#PaymentService
spring.cloud.gateway.server.webmvc.routes[2].id=PaymentService
spring.cloud.gateway.server.webmvc.routes[2].uri=${PAYMENT_SERVICE_URL}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/transfers/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1

#TransactionHistoryService
spring.cloud.gateway.server.webmvc.routes[3].id=TransactionHistoryService
spring.cloud.gateway.server.webmvc.routes[3].uri=${TRANSACTION_SERVICE_URL}
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/transactions/history/**
spring.cloud.gateway.server.webmvc.routes[3].filters[0]=StripPrefix=1