spring.application.name=ProjectGateway
server.port=8084

#CustomerService
spring.cloud.gateway.server.webmvc.routes[0].id=CustomerService
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8080
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/users/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

#AccountService
spring.cloud.gateway.server.webmvc.routes[1].id=AccountService
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/accounts/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

#PaymentService
spring.cloud.gateway.server.webmvc.routes[2].id=PaymentService
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/transfers/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1
