package com.example.customerservice.Model.Mapper;

import com.example.customerservice.Model.Dto.UserCreationDto;
import com.example.customerservice.Model.Dto.UserDto;
import com.example.customerservice.Model.Entity.User;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface UserMapper {

    User mapToUser(UserDto userDto);

    UserDto maptoUserDto(User user);

    // the userCreationDto doesn't have an id Field , because the user shouldn't insert id its generated by jpa
    @Mapping(target = "id" , ignore = true)
    User mapToUser(UserCreationDto userCreationDto);

}
